use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "AsterDrive API",
        version = "0.1.0",
        description = "Self-hosted cloud storage API",
        license(name = "MIT"),
    ),
    paths(
        crate::api::routes::auth::login,
        crate::api::routes::auth::register,
        crate::api::routes::auth::refresh,
        crate::api::routes::health::health,
        crate::api::routes::health::ready,
        crate::api::routes::files::upload,
        crate::api::routes::files::get_file,
        crate::api::routes::files::download,
        crate::api::routes::files::delete_file,
        crate::api::routes::files::patch_file,
        crate::api::routes::folders::list_root,
        crate::api::routes::folders::create_folder,
        crate::api::routes::folders::list_folder,
        crate::api::routes::folders::delete_folder,
        crate::api::routes::folders::patch_folder,
        crate::api::routes::admin::list_policies,
        crate::api::routes::admin::create_policy,
        crate::api::routes::admin::get_policy,
        crate::api::routes::admin::delete_policy,
    ),
    components(
        schemas(
            crate::api::error_code::ErrorCode,
            crate::api::response::TokenResponse,
            crate::api::response::RefreshResponse,
            crate::api::response::FolderContentsResponse,
            crate::api::response::HealthResponse,
            crate::entities::user::Model,
            crate::entities::file::Model,
            crate::entities::folder::Model,
            crate::entities::storage_policy::Model,
            crate::types::UserRole,
            crate::types::UserStatus,
            crate::types::DriverType,
            crate::api::routes::auth::RegisterReq,
            crate::api::routes::auth::LoginReq,
            crate::api::routes::auth::RefreshReq,
            crate::api::routes::files::FileQuery,
            crate::api::routes::files::PatchFileReq,
            crate::api::routes::folders::CreateFolderReq,
            crate::api::routes::folders::PatchFolderReq,
            crate::api::routes::admin::CreatePolicyReq,
        ),
    ),
    tags(
        (name = "auth", description = "Authentication"),
        (name = "files", description = "File operations"),
        (name = "folders", description = "Folder operations"),
        (name = "admin", description = "Admin operations"),
        (name = "health", description = "Health checks"),
    ),
)]
pub struct ApiDoc;
